import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# ==========================================
# Part 1: Total Revenue by Channel - 2024
# ==========================================

# Set the title of the app
st.title("Total Revenue by Channel – 2024")

# Load the CSV file
@st.cache_data
def load_data():
    try:
        # Assuming 2024.csv is in the same directory
        df = pd.read_csv("2024.csv")
        return df
    except FileNotFoundError:
        return None

df = load_data()

if df is not None:
    # Ensure required columns exist
    if 'channel' in df.columns and 'revenue' in df.columns:
        
        # --- Optional Enhancement: Dropdown Filter ---
        # Get unique channels and add an "All Channels" option
        channel_options = ["All Channels"] + list(df['channel'].unique())
        selected_channel = st.selectbox("Select a specific channel or view all:", channel_options)
        
        # Filter the dataframe based on selection
        if selected_channel != "All Channels":
            filtered_df = df[df['channel'] == selected_channel]
        else:
            filtered_df = df
            
        # Group by channel and calculate total revenue
        grouped_df = filtered_df.groupby('channel', as_index=False)['revenue'].sum()

        st.subheader("Revenue Chart")

        # Create a Bar Chart using Matplotlib to strictly control axis labels
        fig, ax = plt.subplots(figsize=(8, 5))
        bars = ax.bar(grouped_df['channel'], grouped_df['revenue'], color='#4C78A8')
        
        # Set explicitly required labels
        ax.set_xlabel("Channel", fontsize=12, fontweight='bold')
        ax.set_ylabel("Total Revenue", fontsize=12, fontweight='bold')
        
        # Add values on top of the bars for better readability
        for bar in bars:
            yval = bar.get_height()
            ax.text(bar.get_x() + bar.get_width()/2, yval, f'${yval:,.0f}', ha='center', va='bottom')

        # Display the Matplotlib chart in Streamlit
        st.pyplot(fig)
        
        # Display the grouped revenue data in a table below the chart
        st.subheader("Revenue Data Table")
        
        # Formatting revenue with dollar sign for presentation
        styled_df = grouped_df.style.format({"revenue": "${:,.2f}"})
        st.dataframe(styled_df, use_container_width=True, hide_index=True)

    else:
        st.error("The file '2024.csv' does not contain the required 'channel' and 'revenue' columns.")
else:
    st.error("Could not find '2024.csv'. Please make sure the file is in the same folder as this script.")

st.markdown("---")

# ==========================================
# Part 2: Not On-Time Deliveries by Area
# ==========================================

# Title for the second section
st.title("Not On-Time Deliveries by Area")

# Load the delay status CSV file
@st.cache_data
def load_delay_data():
    try:
        df_delay = pd.read_csv("delay_status.csv")
        return df_delay
    except FileNotFoundError:
        return None

df_delay = load_delay_data()

if df_delay is not None:
    # Ensure required columns exist
    if 'delivery_status' in df_delay.columns and 'area' in df_delay.columns:
        
        # Filter the data where delivery_status is NOT equal to "on time"
        # Using str.lower() and str.strip() to match variations like "On time" or " on time "
        not_on_time_df = df_delay[df_delay['delivery_status'].astype(str).str.lower().str.strip() != "on time"]
        
        # Group the filtered data by area and calculate the count
        # .size() counts the number of occurrences for each group
        delay_counts = not_on_time_df.groupby('area', as_index=False).size()
        
        # Rename the 'size' column generated by .size() to 'Number of Not On-Time Deliveries'
        delay_counts.rename(columns={'size': 'Number of Not On-Time Deliveries'}, inplace=True)
        
        st.subheader("Delayed Deliveries Chart")
        
        # Create a bar chart
        fig2, ax2 = plt.subplots(figsize=(8, 5))
        bars2 = ax2.bar(delay_counts['area'], delay_counts['Number of Not On-Time Deliveries'], color='#E45756')
        
        # Add appropriate axis labels
        ax2.set_xlabel("Area", fontsize=12, fontweight='bold')
        ax2.set_ylabel("Number of Not On-Time Deliveries", fontsize=12, fontweight='bold')
        
        # Formatter to ensure Y-axis uses integers (no 1.5, 2.5 counts)
        from matplotlib.ticker import MaxNLocator
        ax2.yaxis.set_major_locator(MaxNLocator(integer=True))
        
        # Add labels on top of the bars
        for bar in bars2:
            yval = bar.get_height()
            ax2.text(bar.get_x() + bar.get_width()/2, yval, f'{yval}', ha='center', va='bottom')
            
        # Display the chart in Streamlit
        st.pyplot(fig2)
        
        # Display the grouped result as a table below the chart
        st.subheader("Delayed Deliveries Data Table")
        st.dataframe(delay_counts, use_container_width=True, hide_index=True)
        
    else:
        st.error("The file 'delay_status.csv' does not contain the required 'delivery_status' and 'area' columns.")
else:
    st.error("Could not find 'delay_status.csv'. Please make sure the file is in the same folder as this script.")

st.markdown("---")

# ==========================================
# Part 3: Product Stock Value Distribution
# ==========================================

# Title for the third section
st.title("Product Stock Value Distribution")

# Load the product CSV file
@st.cache_data
def load_product_data():
    try:
        df_product = pd.read_csv("max_products.csv")
        return df_product
    except FileNotFoundError:
        return None

df_product = load_product_data()

if df_product is not None:
    # Ensure required columns exist
    if 'product_name' in df_product.columns and 'total_stock' in df_product.columns and 'sold_price' in df_product.columns:
        
        # Convert columns to numeric in case they were parsed as strings
        df_product['total_stock'] = pd.to_numeric(df_product['total_stock'], errors='coerce').fillna(0)
        df_product['sold_price'] = pd.to_numeric(df_product['sold_price'], errors='coerce').fillna(0)

        # Create new calculated column stock_value
        df_product['stock_value'] = df_product['total_stock'] * df_product['sold_price']
        
        # Group the data by product_name
        stock_val_data = df_product.groupby('product_name', as_index=False)['stock_value'].sum()
        
        st.subheader("Stock Value Distribution Chart")
        
        # Create a pie chart
        fig3, ax3 = plt.subplots(figsize=(10, 8))
        
        colors3 = plt.cm.Set3.colors if hasattr(plt.cm, 'Set3') else None
        
        # Display percentage values for each product
        ax3.pie(
            stock_val_data['stock_value'], 
            labels=stock_val_data['product_name'], 
            autopct='%1.1f%%',
            startangle=140, 
            colors=colors3,
            textprops={'fontsize': 10, 'fontweight': 'bold'}
        )
        
        ax3.axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle.
        
        # Add a title to the Matplotlib chart itself
        ax3.set_title("Total Stock Value by Product", fontsize=14, fontweight='bold', pad=20)
        
        # Display the chart in Streamlit
        st.pyplot(fig3)
        
        # Display the product data and calculated stock value in a table below the chart
        st.subheader("Product Stock Value Data Table")
        
        # Format the relevant columns
        display_df = df_product[['product_name', 'total_stock', 'sold_price', 'stock_value']]
        styled_stock_data = display_df.style.format({
            "total_stock": "{:,.0f}",
            "sold_price": "${:,.2f}",
            "stock_value": "${:,.2f}"
        })
        
        st.dataframe(styled_stock_data, use_container_width=True, hide_index=True)
        
    else:
        st.error("The file does not contain the required 'product_name', 'total_stock', and 'sold_price' columns.")
else:
    st.error("Could not find 'max_products.csv'. Please make sure the file is in the same folder as this script.")
